### ISSUE TITLE
xcframework issue: "mapped file has no cdhash, completely unsigned?"

### ISSUE THREAD

**Issue by salling** [KatalysatorAB/glimr-ios-lite#4]
dyld: Library not loaded: @rpath/GLGeoRealtime.framework/GLGeoRealtime
  Referenced from: /private/var/containers/Bundle/Application/3954EA0A-1B4C-47B1-9C00-5F34D540DD64/AB.app/Frameworks/<redacted>
  Reason: no suitable image found.  Did find:
	/private/var/containers/Bundle/Application/3954EA0A-1B4C-47B1-9C00-5F34D540DD64/AB.app/Frameworks/<redacted>/Frameworks/GLGeoRealtime.framework/GLGeoRealtime: code signature in (/private/var/containers/Bundle/Application/3954EA0A-1B4C-47B1-9C00-5F34D540DD64/AB.app/Frameworks/<redacted>/Frameworks/GLGeoRealtime.framework/GLGeoRealtime) not valid for use in process using Library Validation: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.

**Comment by svenroed** [comment]
hi @salling,

thanks for noting this issue. 

we switched back to using the old way of building frameworks due to a couple of problems we encountered with .xcframeworks. 

we will do a retake on the xcframework within the next days and weeks. We probably remove it until then to not cause any additional confusion in this repository.

**Comment by salling** [comment]
Understood, but understand that we're really keen to move over to Swift Package Manager as soon as possible.

**Comment by svenroed** [comment]
ah, that's why you tried to switch. let me look into this the upcoming week.
